//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenterMVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportCall
    {
        public int SupportCallId { get; set; }
        public string SupportCallEmail { get; set; }
        public string SupportCallUserName { get; set; }
        public string SupportCallDescription { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Solved { get; set; }
        public string SolvedByAgentId { get; set; }
        public Nullable<System.DateTime> SolvedOn { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
